version: '3.8'
services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - 8000:80
        working_dir: /var/www/api
        volumes:
            - ./:/var/www/api
            - ./docker/nginx/:/etc/nginx/conf.d/
    php:
        container_name: php
        extra_hosts:
        - host.docker.internal:host-gateway
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        working_dir: /var/www/api
        volumes:
            - .:/var/www/api
            - ./vendor:/var/www/api/vendor
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini